language: python
python:
  - "2.7"
services: mongodb
# command to install dependencies
install: "pip install -r requirements.txt"
# # command to run tests
script:
  - coverage run pymjq/test.py
  - coverage combine
#  - coverage report --omit '/home/travis/virtualenv/python2.7.9/*'
after_success:
  - bash <(curl -s https://codecov.io/bash)
